# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Box image to use
  config.vm.box = "centos/7"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Set up networking 
  config.vm.network "private_network", ip: "192.168.33.34" 

  # Provision Wordpress
  config.vm.provision "shell", path: "install_wordpress.sh"

end
