# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Box image to use
  config.vm.box = "centos/7"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Set up networking 
  config.vm.network "private_network", ip: "192.168.33.33" 

  # Provision Jenkins
  config.vm.provision "shell", inline: <<-SHELL

    # Install wget
    yum -y install wget

    # Install git
    yum -y install git

    # Install packer
    yum -y install zip unzip
    wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip
    unzip packer_1.0.4_linux_amd64.zip
    mv packer /usr/local/bin/.

    # Install java
    wget --header "Cookie: oraclelicense=accept-securebackup-cookie" \
      http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jre-8u144-linux-x64.rpm
    yum -y localinstall jre-8u144-linux-x64.rpm 

    # Install jenkins
    useradd -m jenkins
    cd /home/jenkins
    su - jenkins -c 'wget https://updates.jenkins-ci.org/download/war/2.74/jenkins.war'
    su - jenkins -c 'cp /vagrant/start_jenkins.sh .'
    su - jenkins -c /home/jenkins/start_jenkins.sh

    SHELL
  
end
